version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: System\Api\Dockerfile
    ports:
      - "5000:5000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=surveydb;userId=postgres;password=Pass
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: